# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036b26586fb6ef5d3e886393ec3301479d8f45badb34d608c702d387c0ef3cc67912231b891c3ba41f383b82487792afd931a10cff029d0e3a959d34f007f931

test:
  secret_key_base: d618c88266d43e90a32a26dc2504ebea1992c4d124e56d494cbd701c7f91ff67c1744f13653965dce41acd8ff79a8bcd9d478f4dabba0a24930d8c17e7b85444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
